Enable additional sources
OpenTermsArchive/federation-api pull request #6
Opened 2024-06-10 16:06 UTC by Ndpnt

2024-06-12 08:53 UTC, MattiSG requested changes
The only blocking point is the changelog, as it does not abide by our rules and has a wrong reference.

There is room for improvement in code quality for the tests and the parsing algorithm, which mixes promise style and imperative style and is more complex than necessary. It would benefit from some refactoring. This is acceptable as is if we're short on time.

Overall, this change is an interesting case where, if we knew of deployed instances, it would be easy and relevant to have backward compatibility.

2024-06-12 08:53 UTC, MattiSG commented on CHANGELOG.md
> +_Full changeset and discussions: [#4](https://github.com/OpenTermsArchive/engine/pull/4)._
```suggestion
_Full changeset and discussions: [#6](https://github.com/OpenTermsArchive/engine/pull/6)._
```

2024-06-12 08:53 UTC, MattiSG commented on CHANGELOG.md
> +- **Breaking:** Replaced `collectionsUrl` config entry with `collections` key, now supporting both URLs and directly specified collections. Refer to the [configuration documentation](https://docs.ope
https://github.com/OpenTermsArchive/engine/blob/main/CONTRIBUTING.md#changes-that-impact-users §3

```suggestion
- **Breaking:** Support arbitrary collections as sources; rename `collectionsUrl` config entry into `collections` and wrap it in an array, refer to the [documentation](https://docs.opentermsarchive.org/api/federated/#configuring) for details
```

2024-06-12 08:53 UTC, MattiSG commented on CHANGELOG.md
> +## Unreleased [minor]
If there are breaking changes, shouldn't this be a major?

> If we want to this to be a minor, we could easily add backwards compatibility by taking `collectionsUrl` and wrap it in an array if `collections` is not defined.

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.js
> +    new URL(string); // eslint-disable-line no-new
> Could `return new URL` on a single line 🙂

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.js
> +  (await Promise.allSettled(collectionsConfig.map(async item => {
```suggestion
  (await Promise.allSettled(collectionsConfig.map(async definition => {
```

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.js
> +      collections = await fetch(item).catch(error => {
> I was surprised that our `fetch` parsed as JSON, as it is different from the standard `fetch` API. For another time, calling our wrapper `fetchAsJSON` would save that surprise 🙂

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.js
> +        throw new Error(`Invalid format; an array of collections is expected when fetching ${item}`);
> Extracting to a function such as `getCollectionsFromRemoteList` would make this more readable 🙂

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.js
> +  return collections.filter(collection => {
> I'd find it more supportive of different use cases and clearer to expose `validateCollection` or `isCollectionValid` and let the caller do the `filter` 🙂

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.js
> +    return filterInvalidCollections(collections);
In a promise approach, I'd find it clearer to only fetch in the first step, then chain the resulting array to `filter(validate)`, consider validation failures as rejected promises rather than log, and handle errors as a last step where we actually log (or throw).

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.js
> +  }))).forEach(({ value, reason }) => {
```suggestion
  }))).forEach(({ value, rejectionReason }) => {
```

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.test.js
> +  const COLLECTION_1_OVERRIDEN = { id: COLLECTION_1.id, name: 'Override Collection 1', endpoint: 'http://domain2.example/endpoint' };
> Declare these outside of any `describe`, in multiline.

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.test.js
> +  const COLLECTION_2 = { id: 'collection2', name: 'Collection 2', endpoint: 'http://domain1.example/endpoint' };
I find it surprising that all the collections share the same endpoint, is it on purpose?

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.test.js
> +    it('fetches collections from URLs and includes directly given collections', async () => {
```suggestion
    it('fetches collections from URLs and includes directly defined collections', async () => {
```

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.test.js
> +          .reply(200, [ COLLECTION_1, COLLECTION_2 ]);
> Move this into a shared `before` to decrease complexity and maintenance costs.

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.test.js
> +              COLLECTION_3,
> Adding the third one does not seem necessary.

2024-06-12 08:53 UTC, MattiSG commented on src/services/collections.test.js
> +    context('with invalid collections', () => {
> I feel we are doing functional tests when we should be doing unit tests… shouldn't this be `describe('validate')` rather than `context('invalid collections')`?

2024-06-12 08:53 UTC, MattiSG commented on test/helper.js
> +import nock from 'nock';
> In order to increase discoverability, maybe add a comment explaining that this file is automatically required in every test file when running `npm test`?

2024-06-12 08:53 UTC, MattiSG commented on test/helper.js
> +    endpoint: 'http://collection-1.example/api/v1',
```suggestion
    endpoint: 'http://collection-1.example/collection-api/v1',
```

2024-06-12 08:53 UTC, MattiSG commented on test/helper.js
> +    endpoint: 'https://2.collection.example/api/v1',
```suggestion
    endpoint: 'https://2.collection.example/collection-api/v1',
```

2024-06-12 08:53 UTC, MattiSG commented on src/index.js
> +  logger.error('Without valid collections declared, the process will exit as this API cannot serve any requests');
```suggestion
  logger.error('No valid collection declared, the process will exit as this API cannot fulfil any request');
```

2024-06-12 09:01 UTC, MattiSG commented
See also https://github.com/OpenTermsArchive/federation-api/pull/4#pullrequestreview-1968349408

2024-06-12 12:29 UTC, Ndpnt commented on src/services/collections.js
> +  }))).forEach(({ value, reason }) => {
I prefer to stick to the [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled#reason]

2024-06-12 12:38 UTC, Ndpnt commented on src/services/collections.test.js
> +              COLLECTION_3,
This ensures that filtering does not interrupt the entire process. If we only get the first result, we can't be certain that filtering didn't stop midway.

2024-06-13 09:25 UTC, MattiSG approved these changes
Good comment in the `helper` file!

2024-06-13 09:25 UTC, MattiSG commented on CHANGELOG.md
> +_Full changeset and discussions: [#4](https://github.com/OpenTermsArchive/engine/pull/4) and [#6](https://github.com/OpenTermsArchive/engine/pull/6)._
> The full changeset is only in #6, I'd rather keep a unique reference in the changelog and make sure that the link to #4 is given in #6 🙂

2024-06-13 09:25 UTC, MattiSG commented on CHANGELOG.md
> +- **Breaking:** Support arbitrary collections as sources; rename `collectionsUrl` config entry into `collections` and wrap it in an array, refer to the [documentation](https://docs.opentermsarchive.o
> I'm wondering if it would not be safer to use a permalink (i.e. to the commit in the doc) rather than a doc URL that will not be valid in a few months.

2024-06-13 09:25 UTC, MattiSG commented on src/utils/url.js
> +export function isURL(string) {
> I preferred `isValidURL`, as the URL parser will also check that it is properly formatted.

2024-06-13 09:25 UTC, MattiSG commented on src/services/collections.js
> +      errors.push('the endpoint is not a valid URL');
> Couldn't all this be rewritten as:

```js
if (!isURL(collection.endpoint))
  errors.push('the endpoint is not a valid URL');
```

2024-06-13 09:46 UTC, merged